### ISSUE TITLE
Ainda não leve em consideração!

### ISSUE THREAD

**Issue by fxcosta** [mateussousap/estacionamento#2]
Ainda não leve em consideração o meu pr, deixa eu commitar com mais avanços! Eu me refiro ao seguinte commit #1

**Comment by mateussousap** [comment]
Ok, estou refatorando o código. Muitos dos problemas estão ocorrendo por conta de 'placa' ser uma string.

**Comment by fxcosta** [comment]
OK, essa issue então vai ser fechada e meu pr ignorado já que foi tudo refatorado.
